---
# configures the server and installs the web application

- include: ubuntu.yml

- include: nginx_ssl.yml
  when: deploy_ssl

- include: nginx_no_ssl.yml
  when: not deploy_ssl

- include: git.yml
- include: postgresql.yml
- include: redis.yml
- include: dependencies.yml
- include: wsgi.yml


- name: alert that deployment is complete
  delegate_to: localhost
  when: deployment_alert